#!/usr/bin/env bash

function setup()
{
    echo '>>> Setting up...'

    # Setup environment
    source .env
    export DOCKER_NETWORK \
        DOCKER_IMAGE_PHP \
        DOCKER_IMAGE_NGINX \
        DOCKER_PUBLIC_URL
}

function develop()
{
    echo '>>> Running...'

    docker run -d \
        -e VIRTUAL_HOST=$DOCKER_PUBLIC_URL \
        -v $PWD/:/var/www/html \
        -v $PWD/site.conf:/etc/nginx/conf.d/site.conf \
        --name ${PWD##*/}-nginx \
        --network $DOCKER_NETWORK \
        $DOCKER_IMAGE_NGINX

    docker run \
        -w /usr/src/app \
        --name ${PWD##*/}-node \
        --network $DOCKER_NETWORK \
        --volume $PWD/:/usr/src/app \
        $DOCKER_IMAGE_NODE \
            npm run serve
}

function cleanup()
{
    echo '>>> Cleaning up...'
    docker stop ${PWD##*/}-node
    docker stop ${PWD##*/}-nginx
    docker rm ${PWD##*/}-node
    docker rm ${PWD##*/}-nginx
    echo '>>> Cleanup done. Have a great day!'
}

setup
develop

trap cleanup EXIT SIGINT
